version: "3.7"
services:
  homepage:
    container_name: "nginx"
    image: 0confirmation/homepage
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /root/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
