version: "3.7"
services:
  certbot:
    image: certbot/certbot
    command: ["certonly", "--register-unsafely-without-email", "--agree-tos", "--standalone", "-d", "npm.kool.house"]
    ports:
      - "80:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
