version: "3.7"
services:
  nginx:
    image:
      nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /root/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
  npm-service:
    user:
      0:0
    image:
      verdaccio/verdaccio:latest
    volumes:
      - /root/verdaccio-storage:/verdaccio/storage
