version: "3.7"
services:
  nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /root/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
  rendezvous:
    image: 0confirmation/webrtc-star
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
