version: '3.4'
services:
  keeper:
    image: 0confirmation/keeper
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - "NETWORK=mainnet"
      - "SEED=464986bd2752a100bdbe074c9d679c3c00f2658d044bdb0c2c8dd7c68bf2e1aa"
