version: '3.4'
services:
  nginx:
    image: nginx
    ports:
      - "62443:443"
    volumes:
      - /root/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
  desktop:
    image: x11vnc/desktop
    ports:
      - "5900:5900"
      - "6080:6080"
