version: '3.4'
services:
  nginx:
    image: nginx
    ports:
      - "62443:443"
    volumes:
      - /root/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
  desktop:
    image: 0confirmation/extdev
    build:
      dockerfile: Dockerfile
      context: ./
    cap_add:
      - "SYS_ADMIN"
    volumes:
      - /root/persistence:/persistence
    ports:
      - "2222:22"
